### ISSUE TITLE
Auto Generated Report: Command raised an exception: OperationalError: no such table: AdoptionRequests

### ISSUE THREAD

**Issue by Exohayvan** [Exohayvan/atsuko#13]
**User Message:** !adopt <@636432285050208257>
**Error:** Command raised an exception: OperationalError: no such table: AdoptionRequests
**Traceback:** 
```python
Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/exohayvan/Documents/GitHub/astuko/commands/family.py", line 55, in adopt
    cursor.execute(
sqlite3.OperationalError: no such table: AdoptionRequests

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: no such table: AdoptionRequests
```
**Command:** `adopt`
**Author:** exohayvan#0
**Channel:** atsuko
**Python Version:** `3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]`
**discord.py Version:** `2.2.2`
**OS:** `Linux 5.15.0-75-generic`

**Comment by Exohayvan** [comment]
Fixed, imported requirements properly
