### ISSUE TITLE
Auto Generated Report: Member "a pig" not found.

### ISSUE THREAD

**Issue by Exohayvan** [Exohayvan/atsuko#14]
**User Message:** !adopt a pig
**Error:** Member "a pig" not found.
**Traceback:** 
```python
Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1015, in invoke
    await self.prepare(ctx)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 932, in prepare
    await self._parse_arguments(ctx)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 847, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param, attachments)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 709, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/converter.py", line 1342, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/converter.py", line 1224, in _actual_conversion
    return await converter().convert(ctx, argument)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/converter.py", line 262, in convert
    raise MemberNotFound(argument)
discord.ext.commands.errors.MemberNotFound: Member "a pig" not found.
```
**Command:** `adopt`
**Author:** queencheeky#0
**Channel:** atsuko
**Python Version:** `3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]`
**discord.py Version:** `2.2.2`
**OS:** `Linux 5.15.0-75-generic`

**Comment by Exohayvan** [comment]
Need to add a check for a mention
