### ISSUE TITLE
Auto Generated Report: Command raised an exception: ConnectionError: HTTPSConnectionPool(host='api.anilist.co', port=443): Max retries exceeded with url: /user/ExoHayvan/animelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89b393fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

### ISSUE THREAD

**Issue by Exohayvan** [Exohayvan/atsuko#20]
**User Message:** !watching ExoHayvan
**Error:** Command raised an exception: ConnectionError: HTTPSConnectionPool(host='api.anilist.co', port=443): Max retries exceeded with url: /user/ExoHayvan/animelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89b393fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
**Traceback:** 
```python
Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f89b393fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/exohayvan/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.anilist.co', port=443): Max retries exceeded with url: /user/ExoHayvan/animelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89b393fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/exohayvan/Documents/GitHub/astuko/commands/anilist.py", line 12, in watching
    response = requests.get(f"https://api.anilist.co/user/{username}/animelist")
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.anilist.co', port=443): Max retries exceeded with url: /user/ExoHayvan/animelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89b393fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/exohayvan/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ConnectionError: HTTPSConnectionPool(host='api.anilist.co', port=443): Max retries exceeded with url: /user/ExoHayvan/animelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89b393fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
**Command:** `watching`
**Author:** exohayvan#0
**Channel:** spam
**Python Version:** `3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]`
**discord.py Version:** `2.2.2`
**OS:** `Linux 5.15.0-75-generic`

**Comment by Exohayvan** [comment]
Used incorrect API.
